ifndef LROOT
	LROOT = /usr/local/lick
endif

include $(LROOT)/etc/Make.defs

LIBFILES = $(wildcard *.py)
LIBSUB = nickel_focus/

DIRS = config data gui pkg scripts tests

include $(LROOT)/etc/Make.rules
